
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-04-28T10:58:20.522+01:00
 * Generated source version: 3.0.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "spfinancials",
                      portName = "SPfinancialPort",
                      targetNamespace = "http://swifta.com/subsidiary/mats/serviceprovider/operation/spfinancial/v1.0",
                      wsdlLocation = "/Users/user/Documents/swifta/PaymentSystemAggregator/target/generated/wsdl/SPfinancial.wsdl",
                      endpointInterface = "com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0.SPfinancial")
                      
public class SPfinancialPortImpl implements SPfinancial {

    private static final Logger LOG = Logger.getLogger(SPfinancialPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0.SPfinancial#verifycashoutrequest(java.lang.String  orginatingresourceid ,)java.lang.String  subscriberphonenumber ,)java.lang.String  amount ,)java.lang.String  referencenumber ,)com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension  extensionparameters )*
     */
    public com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Verifycashoutresponse verifycashoutrequest(java.lang.String orginatingresourceid,java.lang.String subscriberphonenumber,java.lang.String amount,java.lang.String referencenumber,com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension extensionparameters) { 
        LOG.info("Executing operation verifycashoutrequest");
        System.out.println(orginatingresourceid);
        System.out.println(subscriberphonenumber);
        System.out.println(amount);
        System.out.println(referencenumber);
        System.out.println(extensionparameters);
        try {
            com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Verifycashoutresponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0.SPfinancial#cashoutrequest(java.lang.String  orginatingresourceid ,)java.lang.String  destinationresourceid ,)java.lang.String  amount ,)java.lang.String  sendingdescription ,)java.lang.String  receivingdescription ,)com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension  extensionparameters )*
     */
    public com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Cashoutresponse cashoutrequest(java.lang.String orginatingresourceid,java.lang.String destinationresourceid,java.lang.String amount,java.lang.String sendingdescription,java.lang.String receivingdescription,com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension extensionparameters) { 
        LOG.info("Executing operation cashoutrequest");
        System.out.println(orginatingresourceid);
        System.out.println(destinationresourceid);
        System.out.println(amount);
        System.out.println(sendingdescription);
        System.out.println(receivingdescription);
        System.out.println(extensionparameters);
        try {
            com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Cashoutresponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0.SPfinancial#balancerequest(java.lang.String  orginatingresourceid ,)com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension  extensionparameters )*
     */
    public com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Balanceresponse balancerequest(java.lang.String orginatingresourceid,com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension extensionparameters) { 
        LOG.info("Executing operation balancerequest");
        System.out.println(orginatingresourceid);
        System.out.println(extensionparameters);
        try {
            com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Balanceresponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0.SPfinancial#transfertobankrequest(java.lang.String  orginatingresourceid ,)java.lang.String  amount ,)java.lang.String  bankcode ,)com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension  extensionparameters )*
     */
    public com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Transfertobankresponse transfertobankrequest(java.lang.String orginatingresourceid,java.lang.String amount,java.lang.String bankcode,com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension extensionparameters) { 
        LOG.info("Executing operation transfertobankrequest");
        System.out.println(orginatingresourceid);
        System.out.println(amount);
        System.out.println(bankcode);
        System.out.println(extensionparameters);
        try {
            com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Transfertobankresponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0.SPfinancial#cashinrequest(java.lang.String  orginatingresourceid ,)java.lang.String  destinationresourceid ,)java.lang.String  amount ,)java.lang.String  sendingdescription ,)java.lang.String  receivingdescription ,)com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension  extensionparameters )*
     */
    public com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Cashinresponse cashinrequest(java.lang.String orginatingresourceid,java.lang.String destinationresourceid,java.lang.String amount,java.lang.String sendingdescription,java.lang.String receivingdescription,com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension extensionparameters) { 
        LOG.info("Executing operation cashinrequest");
        System.out.println(orginatingresourceid);
        System.out.println(destinationresourceid);
        System.out.println(amount);
        System.out.println(sendingdescription);
        System.out.println(receivingdescription);
        System.out.println(extensionparameters);
        try {
            com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Cashinresponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0.SPfinancial#airtimesalesrequest(java.lang.String  orginatingresourceid ,)java.lang.String  beneficiarynumber ,)java.lang.String  serviceprovider ,)java.lang.String  amount ,)com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension  extensionparameters )*
     */
    public com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Airtimesalesresponse airtimesalesrequest(java.lang.String orginatingresourceid,java.lang.String beneficiarynumber,java.lang.String serviceprovider,java.lang.String amount,com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension extensionparameters) { 
        LOG.info("Executing operation airtimesalesrequest");
        System.out.println(orginatingresourceid);
        System.out.println(beneficiarynumber);
        System.out.println(serviceprovider);
        System.out.println(amount);
        System.out.println(extensionparameters);
        try {
            com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Airtimesalesresponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0.SPfinancial#paybillsrequest(java.lang.String  orginatingresourceid ,)java.lang.String  merchantcode ,)java.lang.String  amount ,)java.lang.String  sendingdescription ,)java.lang.String  receivingdescription ,)com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension  extensionparameters )*
     */
    public com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Paybillsresponse paybillsrequest(java.lang.String orginatingresourceid,java.lang.String merchantcode,java.lang.String amount,java.lang.String sendingdescription,java.lang.String receivingdescription,com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension extensionparameters) { 
        LOG.info("Executing operation paybillsrequest");
        System.out.println(orginatingresourceid);
        System.out.println(merchantcode);
        System.out.println(amount);
        System.out.println(sendingdescription);
        System.out.println(receivingdescription);
        System.out.println(extensionparameters);
        try {
            com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Paybillsresponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
