
package com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-04-28T10:58:20.632+01:00
 * Generated source version: 3.0.2
 * 
 */
 
public class SPfinancial_SPfinancialPort_Server{

    protected SPfinancial_SPfinancialPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SPfinancialPortImpl();
        String address = "http://localhost:9090/SPfinancialPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SPfinancial_SPfinancialPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
