/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0;

import java.util.logging.Logger;

import com.swifta.spfinancial.utils.TransactionService;

/**
 * This class was generated by Apache CXF 3.0.2 2014-11-11T22:51:40.045+01:00
 * Generated source version: 3.0.2
 * 
 */

@javax.jws.WebService(serviceName = "spfinancials", portName = "SPfinancialPort", targetNamespace = "http://swifta.com/subsidiary/mats/serviceprovider/operation/spfinancial/v1.0", wsdlLocation = "/home/ec2-user/wsdl/SPFinancial.wsdl",
// wsdlLocation =
// "/Users/user/Documents/swifta/SPfinancial/src/main/webapp/WEB-INF/wsdl/SPFinancial.wsdl",
endpointInterface = "com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0.SPfinancial")
public class SPfinancialPortImpl implements SPfinancial {

	private static final Logger LOG = Logger
			.getLogger(SPfinancialPortImpl.class.getName());
	private TransactionService transactionService = new TransactionService();

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0
	 * .SPfinancial#cashinrequest(java.lang.String orginatingresourceid
	 * ,)java.lang.String destinationresourceid ,)java.lang.String amount
	 * ,)java.lang.String sendingdescription ,)java.lang.String
	 * receivingdescription
	 * ,)com.swifta.subsidiary.mats.serviceprovider.operation
	 * .spfinancial.v1.ParameterExtension extensionparameters )*
	 */
	public com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Cashinresponse cashinrequest(
			java.lang.String orginatingresourceid,
			java.lang.String destinationresourceid,
			java.lang.String amount,
			java.lang.String sendingdescription,
			java.lang.String receivingdescription,
			com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension extensionparameters) {
		LOG.info("Executing operation cashinrequest");
		System.out.println(orginatingresourceid);
		System.out.println(destinationresourceid);
		System.out.println(amount);
		System.out.println(sendingdescription);
		System.out.println(receivingdescription);
		System.out.println(extensionparameters);
		try {
			return transactionService.performCashIn(orginatingresourceid,
					destinationresourceid, amount, sendingdescription,
					receivingdescription, extensionparameters);

		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0
	 * .SPfinancial#cashoutrequest(java.lang.String orginatingresourceid
	 * ,)java.lang.String destinationresourceid ,)java.lang.String amount
	 * ,)java.lang.String sendingdescription ,)java.lang.String
	 * receivingdescription
	 * ,)com.swifta.subsidiary.mats.serviceprovider.operation
	 * .spfinancial.v1.ParameterExtension extensionparameters )*
	 */
	public com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.Cashoutresponse cashoutrequest(
			java.lang.String orginatingresourceid,
			java.lang.String destinationresourceid,
			java.lang.String amount,
			java.lang.String sendingdescription,
			java.lang.String receivingdescription,
			com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1.ParameterExtension extensionparameters) {
		LOG.info("Executing operation cashoutrequest");
		System.out.println(orginatingresourceid);
		System.out.println(destinationresourceid);
		System.out.println(amount);
		System.out.println(sendingdescription);
		System.out.println(receivingdescription);
		System.out.println(extensionparameters);
		try {
			return transactionService.performCashOut(orginatingresourceid,
					destinationresourceid, amount, sendingdescription,
					receivingdescription, extensionparameters);

		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
