package com.swifta.subsidiary.mats.serviceprovider.operation.spfinancial.v1_0;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-10-25T17:40:09.288+03:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "spfinancials", 
                  wsdlLocation = "/Users/modupealadeojebi/Documents/java2wsdl/version1/PaymentSystemAggregator/target/generated/wsdl/SPfinancial.wsdl",
                  targetNamespace = "http://swifta.com/subsidiary/mats/serviceprovider/operation/spfinancial/v1.0") 
public class Spfinancials extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://swifta.com/subsidiary/mats/serviceprovider/operation/spfinancial/v1.0", "spfinancials");
    public final static QName SPfinancialPort = new QName("http://swifta.com/subsidiary/mats/serviceprovider/operation/spfinancial/v1.0", "SPfinancialPort");
    static {
        URL url = Spfinancials.class.getResource("/Users/modupealadeojebi/Documents/java2wsdl/version1/PaymentSystemAggregator/target/generated/wsdl/SPfinancial.wsdl");
        if (url == null) {
            url = Spfinancials.class.getClassLoader().getResource("/Users/modupealadeojebi/Documents/java2wsdl/version1/PaymentSystemAggregator/target/generated/wsdl/SPfinancial.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(Spfinancials.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/modupealadeojebi/Documents/java2wsdl/version1/PaymentSystemAggregator/target/generated/wsdl/SPfinancial.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public Spfinancials(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Spfinancials(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Spfinancials() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Spfinancials(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Spfinancials(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Spfinancials(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SPfinancial
     */
    @WebEndpoint(name = "SPfinancialPort")
    public SPfinancial getSPfinancialPort() {
        return super.getPort(SPfinancialPort, SPfinancial.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SPfinancial
     */
    @WebEndpoint(name = "SPfinancialPort")
    public SPfinancial getSPfinancialPort(WebServiceFeature... features) {
        return super.getPort(SPfinancialPort, SPfinancial.class, features);
    }

}
